# Generated by Django 4.1.3 on 2022-11-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sewer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idn", models.CharField(max_length=20, verbose_name="고유번호")),
                ("gubn", models.CharField(max_length=20, verbose_name="구분코드")),
                ("gubn_nam", models.CharField(max_length=20, verbose_name="구분명")),
                ("mea_ymd", models.DateTimeField(verbose_name="측정일자")),
                ("mea_wal", models.FloatField(verbose_name="측정수위")),
                ("sig_sta", models.CharField(max_length=20, verbose_name="통신상태")),
                ("remark", models.TextField(verbose_name="위치정보")),
            ],
            options={
                "verbose_name": "하수관",
                "verbose_name_plural": "하수관",
            },
        ),
    ]
