# Generated by Django 4.1.3 on 2022-11-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rainfall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rainguage_code", models.FloatField(verbose_name="강우량계 코드")),
                (
                    "raingauge_name",
                    models.CharField(max_length=20, verbose_name="강우량계명"),
                ),
                ("gu_code", models.FloatField(verbose_name="구청 코드")),
                ("gu_name", models.CharField(max_length=20, verbose_name="구청명")),
                ("rainfall10", models.CharField(max_length=20, verbose_name="10분우량")),
                ("receive_time", models.DateTimeField(verbose_name="자료수집 시각")),
            ],
            options={
                "verbose_name": "강우량",
                "verbose_name_plural": "강우량",
            },
        ),
    ]
